---
title: "Simulation Study"
author: "Thomas Debray"
date: "This report was generated on `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
# Set document properties
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

source("../R/functions.r")
source("../R/sim.r")

library(ggplot2)
library(kableExtra)
```

```{r}
results <- runSim()

ggdat <- data.frame(est = c(results$naive, results$NNM, results$OFM, results$IPW, results$TDW),
                    method = c(rep("Naive", nrow(results)), rep("NNM", nrow(results)), rep("OFM", nrow(results)),
                               rep("IPW", nrow(results)), rep("TDW", nrow(results))),
                    scenario = rep(results$scenario, 5),
                    hte = rep(results$hte, 5))

ggdat$scenario <- factor(ggdat$scenario, 
                         levels = c("A", "B", "C"), 
                         labels = c("Weak confounding", "Moderate confounding", "Strong confounding"))
ggdat$hte <- factor(ggdat$hte, 
                    levels = c("no", "yes"), 
                    labels = c("no effect modification", "effect modification"))
                                        

ggplot(ggdat, aes(x = method, y = est)) + 
  geom_boxplot(aes(group = method)) +
  facet_wrap(~scenario + hte) +
  ylab("ATT")
```



